apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: es
  namespace: logging
  generation: 1
  labels:
    appgroup: ''
  annotations:
    container.io/container-0: https://console.huaweicloud.com/swr/dockerimage/nginx.png
    description: ''
spec:
  serviceName: elasticsearch
  replicas: 3
  selector:
    matchLabels:
      app: elasticsearch
      failure-domain.beta.kubernetes.io/region: cn-east-3
      failure-domain.beta.kubernetes.io/zone: cn-east-3a
  template:
    metadata:
      labels:
        app: elasticsearch
        failure-domain.beta.kubernetes.io/region: cn-east-3
        failure-domain.beta.kubernetes.io/zone: cn-east-3a
      annotations:
        metrics.alpha.kubernetes.io/custom-endpoints: '[{"api":"","path":"","port":"","names":""}]'
        pod.alpha.kubernetes.io/initialized: 'true'
    spec:
      initContainers:
      - name: increase-vm-max-map
        image: swr.cn-east-3.myhuaweicloud.com/efk/busybox
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
      - name: increase-fd-ulimit
        image: busybox
        command: ["sh", "-c", "ulimit -n 65536"]
        securityContext:
          privileged: true
      containers:
      - name: elasticsearch
        image: swr.cn-east-3.myhuaweicloud.com/efk/es:7.6.2
        ports:
        - name: rest
          containerPort: 9200
        - name: inter
          containerPort: 9300
        resources:
          limits:
            cpu: 1000m
          requests:
            cpu: 1000m
        volumeMounts:
        - name: efk-data
          mountPath: /usr/share/elasticsearch/data
        env:
        - name: cluster.name
          value: k8s-logs
        - name: node.name
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: cluster.initial_master_nodes
          value: "es-0,es-1,es-2"
        - name: discovery.zen.minimum_master_nodes
          value: "2"
        - name: discovery.seed_hosts
          value: "elasticsearch"
        - name: ES_JAVA_OPTS
          value: "-Xms512m -Xmx512m"
        - name: network.host
          value: "0.0.0.0"
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      imagePullSecrets:
        - name: default-secret
      affinity: {}
      schedulerName: default-scheduler
  volumeClaimTemplates:
    - metadata:
        name: efk-data
        namespace: logging
        annotations: {}
        enable: true
      spec:
        accessModes:
          - ReadWriteMany
        resources:
          requests:
            storage: 30Gi
        storageClassName: csi-nas  

